[2024-05-28T12:33:53.208+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: loading_to_bigquerry.load_territories_to_bq manual__2024-05-28T12:32:41.747408+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
