[2024-05-28T12:31:04.694+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: loading_to_bigquerry.load_customers_to_bq manual__2024-05-28T12:30:00.085384+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
