[2024-05-23T15:47:34.304+0000] {processor.py:161} INFO - Started process (PID=1180) to work on /opt/airflow/dags/test.py
[2024-05-23T15:47:34.320+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:47:34.549+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:47:34.523+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:47:34.940+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:47:34.801+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:47:34.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:47:35.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 1.383 seconds
[2024-05-23T15:48:06.012+0000] {processor.py:161} INFO - Started process (PID=1193) to work on /opt/airflow/dags/test.py
[2024-05-23T15:48:06.021+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:48:06.034+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:48:06.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:48:06.102+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:48:06.085+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:48:06.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:48:06.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.210 seconds
[2024-05-23T15:48:36.588+0000] {processor.py:161} INFO - Started process (PID=1200) to work on /opt/airflow/dags/test.py
[2024-05-23T15:48:36.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:48:36.617+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:48:36.616+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:48:36.724+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:48:36.693+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:48:36.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:48:36.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.293 seconds
[2024-05-23T15:49:10.196+0000] {processor.py:161} INFO - Started process (PID=1207) to work on /opt/airflow/dags/test.py
[2024-05-23T15:49:10.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:49:10.433+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:49:10.336+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:49:11.017+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:49:10.890+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:49:11.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:49:11.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 1.051 seconds
[2024-05-23T15:49:42.165+0000] {processor.py:161} INFO - Started process (PID=1215) to work on /opt/airflow/dags/test.py
[2024-05-23T15:49:42.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:49:42.179+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:49:42.177+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:49:42.239+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:49:42.225+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:49:42.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:49:42.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.162 seconds
[2024-05-23T15:50:12.484+0000] {processor.py:161} INFO - Started process (PID=1222) to work on /opt/airflow/dags/test.py
[2024-05-23T15:50:12.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:50:12.509+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:50:12.508+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:50:12.608+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:50:12.588+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:50:12.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:50:12.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.267 seconds
[2024-05-23T15:50:42.859+0000] {processor.py:161} INFO - Started process (PID=1229) to work on /opt/airflow/dags/test.py
[2024-05-23T15:50:42.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:50:42.873+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:50:42.872+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:50:42.929+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:50:42.915+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:50:42.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:50:43.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.173 seconds
[2024-05-23T15:51:13.328+0000] {processor.py:161} INFO - Started process (PID=1236) to work on /opt/airflow/dags/test.py
[2024-05-23T15:51:13.331+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:51:13.339+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:51:13.338+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:51:13.405+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:51:13.390+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:51:13.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:51:13.468+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.169 seconds
[2024-05-23T15:51:43.909+0000] {processor.py:161} INFO - Started process (PID=1243) to work on /opt/airflow/dags/test.py
[2024-05-23T15:51:43.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:51:43.923+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:51:43.922+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:51:44.009+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:51:43.993+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:51:44.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:51:44.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.183 seconds
[2024-05-23T15:52:14.293+0000] {processor.py:161} INFO - Started process (PID=1250) to work on /opt/airflow/dags/test.py
[2024-05-23T15:52:14.296+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:52:14.302+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:52:14.301+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:52:14.351+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:52:14.337+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:52:14.356+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:52:14.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.125 seconds
[2024-05-23T15:52:45.061+0000] {processor.py:161} INFO - Started process (PID=1257) to work on /opt/airflow/dags/test.py
[2024-05-23T15:52:45.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:52:45.069+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:52:45.068+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:52:45.132+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:52:45.117+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:52:45.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:52:45.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.157 seconds
[2024-05-23T15:53:15.432+0000] {processor.py:161} INFO - Started process (PID=1265) to work on /opt/airflow/dags/test.py
[2024-05-23T15:53:15.437+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:53:15.445+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:53:15.444+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:53:15.505+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:53:15.494+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:53:15.510+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:53:15.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.196 seconds
[2024-05-23T15:53:46.117+0000] {processor.py:161} INFO - Started process (PID=1272) to work on /opt/airflow/dags/test.py
[2024-05-23T15:53:46.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:53:46.137+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:53:46.135+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:53:46.216+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:53:46.202+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:53:46.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:53:46.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.190 seconds
[2024-05-23T15:54:16.714+0000] {processor.py:161} INFO - Started process (PID=1279) to work on /opt/airflow/dags/test.py
[2024-05-23T15:54:16.718+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:54:16.725+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:54:16.724+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:54:16.821+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:54:16.808+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:54:16.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:54:16.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.215 seconds
[2024-05-23T15:54:47.493+0000] {processor.py:161} INFO - Started process (PID=1286) to work on /opt/airflow/dags/test.py
[2024-05-23T15:54:47.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:54:47.521+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:54:47.517+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:54:47.573+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:54:47.559+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:54:47.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:54:47.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.160 seconds
[2024-05-23T15:55:18.527+0000] {processor.py:161} INFO - Started process (PID=1293) to work on /opt/airflow/dags/test.py
[2024-05-23T15:55:18.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:55:18.544+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:55:18.543+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:55:18.909+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:55:18.820+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:55:18.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:55:19.160+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.713 seconds
[2024-05-23T15:55:50.073+0000] {processor.py:161} INFO - Started process (PID=1300) to work on /opt/airflow/dags/test.py
[2024-05-23T15:55:50.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:55:50.096+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:55:50.094+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:55:50.164+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:55:50.141+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:55:50.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:55:50.237+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.185 seconds
[2024-05-23T15:56:20.799+0000] {processor.py:161} INFO - Started process (PID=1307) to work on /opt/airflow/dags/test.py
[2024-05-23T15:56:20.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:56:20.813+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:56:20.812+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:56:20.882+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:56:20.863+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:56:20.889+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:56:20.958+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.180 seconds
[2024-05-23T15:56:51.275+0000] {processor.py:161} INFO - Started process (PID=1314) to work on /opt/airflow/dags/test.py
[2024-05-23T15:56:51.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:56:51.290+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:56:51.289+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:56:51.368+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:56:51.355+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:56:51.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:56:51.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.203 seconds
[2024-05-23T15:57:22.006+0000] {processor.py:161} INFO - Started process (PID=1321) to work on /opt/airflow/dags/test.py
[2024-05-23T15:57:22.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:57:22.015+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:57:22.014+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:57:22.073+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:57:22.059+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:57:22.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:57:22.133+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.154 seconds
[2024-05-23T15:57:52.628+0000] {processor.py:161} INFO - Started process (PID=1328) to work on /opt/airflow/dags/test.py
[2024-05-23T15:57:52.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:57:52.635+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:57:52.634+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:57:52.680+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:57:52.666+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:57:52.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:57:52.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.125 seconds
[2024-05-23T15:58:23.142+0000] {processor.py:161} INFO - Started process (PID=1335) to work on /opt/airflow/dags/test.py
[2024-05-23T15:58:23.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:58:23.156+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:58:23.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:58:23.238+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:58:23.220+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:58:23.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:58:23.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.200 seconds
[2024-05-23T15:58:53.704+0000] {processor.py:161} INFO - Started process (PID=1342) to work on /opt/airflow/dags/test.py
[2024-05-23T15:58:53.706+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:58:53.714+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:58:53.713+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:58:53.887+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:58:53.855+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:58:53.901+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:58:53.970+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.288 seconds
[2024-05-23T15:59:24.780+0000] {processor.py:161} INFO - Started process (PID=1350) to work on /opt/airflow/dags/test.py
[2024-05-23T15:59:24.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:59:24.805+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:59:24.803+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:59:25.254+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:59:25.124+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:59:25.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:59:25.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.708 seconds
[2024-05-23T15:59:56.349+0000] {processor.py:161} INFO - Started process (PID=1357) to work on /opt/airflow/dags/test.py
[2024-05-23T15:59:56.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T15:59:56.371+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:59:56.370+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T15:59:56.518+0000] {logging_mixin.py:188} INFO - [2024-05-23T15:59:56.490+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T15:59:56.539+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T15:59:56.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.345 seconds
[2024-05-23T16:00:27.285+0000] {processor.py:161} INFO - Started process (PID=1364) to work on /opt/airflow/dags/test.py
[2024-05-23T16:00:27.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:00:27.302+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:00:27.300+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:00:27.365+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:00:27.345+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:00:27.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:00:27.472+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.212 seconds
[2024-05-23T16:00:57.832+0000] {processor.py:161} INFO - Started process (PID=1371) to work on /opt/airflow/dags/test.py
[2024-05-23T16:00:57.836+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:00:57.846+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:00:57.844+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:00:57.929+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:00:57.908+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:00:57.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:00:58.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.199 seconds
[2024-05-23T16:01:28.768+0000] {processor.py:161} INFO - Started process (PID=1378) to work on /opt/airflow/dags/test.py
[2024-05-23T16:01:28.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:01:28.799+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:01:28.797+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:01:29.159+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:01:29.110+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:01:29.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:01:29.298+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.568 seconds
[2024-05-23T16:02:00.268+0000] {processor.py:161} INFO - Started process (PID=1385) to work on /opt/airflow/dags/test.py
[2024-05-23T16:02:00.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:02:00.283+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:02:00.280+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:02:00.455+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:02:00.413+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:02:00.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:02:00.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.367 seconds
[2024-05-23T16:02:31.367+0000] {processor.py:161} INFO - Started process (PID=1392) to work on /opt/airflow/dags/test.py
[2024-05-23T16:02:31.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:02:31.384+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:02:31.383+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:02:31.492+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:02:31.464+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:02:31.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:02:31.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.255 seconds
[2024-05-23T16:03:02.174+0000] {processor.py:161} INFO - Started process (PID=1399) to work on /opt/airflow/dags/test.py
[2024-05-23T16:03:02.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:03:02.184+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:03:02.183+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:03:02.236+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:03:02.220+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:03:02.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:03:02.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.136 seconds
[2024-05-23T16:03:32.774+0000] {processor.py:161} INFO - Started process (PID=1407) to work on /opt/airflow/dags/test.py
[2024-05-23T16:03:32.777+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:03:32.796+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:03:32.794+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:03:32.865+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:03:32.844+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:03:32.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:03:32.924+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.175 seconds
[2024-05-23T16:04:03.387+0000] {processor.py:161} INFO - Started process (PID=1414) to work on /opt/airflow/dags/test.py
[2024-05-23T16:04:03.392+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:04:03.426+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:04:03.424+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:04:03.565+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:04:03.528+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:04:03.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:04:03.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.318 seconds
[2024-05-23T16:04:34.009+0000] {processor.py:161} INFO - Started process (PID=1422) to work on /opt/airflow/dags/test.py
[2024-05-23T16:04:34.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:04:34.019+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:04:34.018+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:04:34.069+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:04:34.057+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:04:34.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:04:34.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.140 seconds
[2024-05-23T16:05:04.582+0000] {processor.py:161} INFO - Started process (PID=1429) to work on /opt/airflow/dags/test.py
[2024-05-23T16:05:04.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:05:04.601+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:05:04.600+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:05:04.648+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:05:04.637+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:05:04.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:05:04.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.139 seconds
[2024-05-23T16:05:35.071+0000] {processor.py:161} INFO - Started process (PID=1437) to work on /opt/airflow/dags/test.py
[2024-05-23T16:05:35.075+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:05:35.082+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:05:35.081+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:05:35.143+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:05:35.127+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:05:35.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:05:35.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.150 seconds
[2024-05-23T16:06:05.495+0000] {processor.py:161} INFO - Started process (PID=1444) to work on /opt/airflow/dags/test.py
[2024-05-23T16:06:05.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:06:05.506+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:06:05.505+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:06:05.566+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:06:05.551+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:06:05.572+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:06:05.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.159 seconds
[2024-05-23T16:06:36.107+0000] {processor.py:161} INFO - Started process (PID=1451) to work on /opt/airflow/dags/test.py
[2024-05-23T16:06:36.112+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:06:36.119+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:06:36.118+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:06:36.181+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:06:36.168+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:06:36.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:06:36.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.153 seconds
[2024-05-23T16:07:06.576+0000] {processor.py:161} INFO - Started process (PID=1459) to work on /opt/airflow/dags/test.py
[2024-05-23T16:07:06.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:07:06.585+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:07:06.584+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:07:06.631+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:07:06.617+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:07:06.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:07:06.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.145 seconds
[2024-05-23T16:07:37.777+0000] {processor.py:161} INFO - Started process (PID=1466) to work on /opt/airflow/dags/test.py
[2024-05-23T16:07:37.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:07:37.794+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:07:37.790+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:07:37.893+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:07:37.864+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:07:37.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:07:37.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.243 seconds
[2024-05-23T16:08:08.212+0000] {processor.py:161} INFO - Started process (PID=1473) to work on /opt/airflow/dags/test.py
[2024-05-23T16:08:08.222+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:08:08.228+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:08:08.227+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:08:08.380+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:08:08.327+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:08:08.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:08:08.572+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.408 seconds
[2024-05-23T16:08:39.451+0000] {processor.py:161} INFO - Started process (PID=1480) to work on /opt/airflow/dags/test.py
[2024-05-23T16:08:39.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:08:39.598+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:08:39.597+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:08:40.167+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:08:40.141+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:08:40.178+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:08:40.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 1.048 seconds
[2024-05-23T16:09:10.950+0000] {processor.py:161} INFO - Started process (PID=1487) to work on /opt/airflow/dags/test.py
[2024-05-23T16:09:10.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:09:10.970+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:09:10.969+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:09:11.058+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:09:11.046+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:09:11.071+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:09:11.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.236 seconds
[2024-05-23T16:09:41.467+0000] {processor.py:161} INFO - Started process (PID=1494) to work on /opt/airflow/dags/test.py
[2024-05-23T16:09:41.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:09:41.489+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:09:41.487+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:09:41.555+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:09:41.526+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:09:41.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:09:41.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.217 seconds
[2024-05-23T16:10:11.999+0000] {processor.py:161} INFO - Started process (PID=1501) to work on /opt/airflow/dags/test.py
[2024-05-23T16:10:12.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:10:12.015+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:10:12.012+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:10:12.066+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:10:12.055+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:10:12.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:10:12.128+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.160 seconds
[2024-05-23T16:10:42.589+0000] {processor.py:161} INFO - Started process (PID=1508) to work on /opt/airflow/dags/test.py
[2024-05-23T16:10:42.593+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:10:42.602+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:10:42.601+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:10:42.671+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:10:42.651+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:10:42.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:10:42.746+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.175 seconds
[2024-05-23T16:11:13.025+0000] {processor.py:161} INFO - Started process (PID=1516) to work on /opt/airflow/dags/test.py
[2024-05-23T16:11:13.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:11:13.034+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:11:13.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:11:13.099+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:11:13.085+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:11:13.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:11:13.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.174 seconds
[2024-05-23T16:11:43.486+0000] {processor.py:161} INFO - Started process (PID=1523) to work on /opt/airflow/dags/test.py
[2024-05-23T16:11:43.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:11:43.498+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:11:43.497+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:11:43.549+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:11:43.536+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:11:43.557+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:11:43.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.133 seconds
[2024-05-23T16:12:14.085+0000] {processor.py:161} INFO - Started process (PID=1530) to work on /opt/airflow/dags/test.py
[2024-05-23T16:12:14.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:12:14.091+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:12:14.090+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:12:14.157+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:12:14.143+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:12:14.166+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:12:14.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.153 seconds
[2024-05-23T16:12:45.083+0000] {processor.py:161} INFO - Started process (PID=1537) to work on /opt/airflow/dags/test.py
[2024-05-23T16:12:45.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:12:45.107+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:12:45.105+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:12:45.211+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:12:45.190+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:12:45.230+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:12:45.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.266 seconds
[2024-05-23T16:13:16.930+0000] {processor.py:161} INFO - Started process (PID=1544) to work on /opt/airflow/dags/test.py
[2024-05-23T16:13:16.934+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:13:16.951+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:13:16.949+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:13:17.731+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:13:17.573+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:13:17.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:13:18.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 1.195 seconds
[2024-05-23T16:13:50.864+0000] {processor.py:161} INFO - Started process (PID=1551) to work on /opt/airflow/dags/test.py
[2024-05-23T16:13:50.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:13:50.983+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:13:50.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:13:51.605+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:13:51.472+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:13:51.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:13:52.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 1.274 seconds
[2024-05-23T16:14:23.050+0000] {processor.py:161} INFO - Started process (PID=1558) to work on /opt/airflow/dags/test.py
[2024-05-23T16:14:23.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:14:23.081+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:14:23.079+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:14:23.197+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:14:23.167+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:14:23.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:14:23.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.426 seconds
[2024-05-23T16:14:53.832+0000] {processor.py:161} INFO - Started process (PID=1565) to work on /opt/airflow/dags/test.py
[2024-05-23T16:14:53.835+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:14:53.843+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:14:53.841+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:14:53.906+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:14:53.893+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:14:53.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:14:53.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.182 seconds
[2024-05-23T16:15:24.462+0000] {processor.py:161} INFO - Started process (PID=1572) to work on /opt/airflow/dags/test.py
[2024-05-23T16:15:24.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:15:24.482+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:15:24.480+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:15:24.617+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:15:24.577+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:15:24.635+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:15:24.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.326 seconds
[2024-05-23T16:15:54.980+0000] {processor.py:161} INFO - Started process (PID=1579) to work on /opt/airflow/dags/test.py
[2024-05-23T16:15:54.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:15:54.990+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:15:54.989+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:15:55.043+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:15:55.026+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:15:55.050+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:15:55.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.134 seconds
[2024-05-23T16:16:25.557+0000] {processor.py:161} INFO - Started process (PID=1586) to work on /opt/airflow/dags/test.py
[2024-05-23T16:16:25.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:16:25.577+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:16:25.575+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:16:25.694+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:16:25.662+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:16:25.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:16:25.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.292 seconds
[2024-05-23T16:16:56.026+0000] {processor.py:161} INFO - Started process (PID=1593) to work on /opt/airflow/dags/test.py
[2024-05-23T16:16:56.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:16:56.045+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:16:56.043+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:16:56.144+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:16:56.120+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:16:56.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:16:56.246+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.250 seconds
[2024-05-23T16:17:26.699+0000] {processor.py:161} INFO - Started process (PID=1600) to work on /opt/airflow/dags/test.py
[2024-05-23T16:17:26.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:17:26.706+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:17:26.705+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:17:26.756+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:17:26.739+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:17:26.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:17:26.809+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.123 seconds
[2024-05-23T16:17:57.560+0000] {processor.py:161} INFO - Started process (PID=1607) to work on /opt/airflow/dags/test.py
[2024-05-23T16:17:57.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:17:57.569+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:17:57.568+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:17:57.613+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:17:57.601+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:17:57.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:17:57.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.174 seconds
[2024-05-23T16:18:27.861+0000] {processor.py:161} INFO - Started process (PID=1614) to work on /opt/airflow/dags/test.py
[2024-05-23T16:18:27.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:18:27.865+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:18:27.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:18:27.894+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:18:27.885+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:18:27.898+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:18:27.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.076 seconds
[2024-05-23T16:18:58.123+0000] {processor.py:161} INFO - Started process (PID=1621) to work on /opt/airflow/dags/test.py
[2024-05-23T16:18:58.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:18:58.130+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:18:58.129+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:18:58.184+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:18:58.170+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:18:58.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:18:58.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.135 seconds
[2024-05-23T16:19:28.442+0000] {processor.py:161} INFO - Started process (PID=1628) to work on /opt/airflow/dags/test.py
[2024-05-23T16:19:28.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:19:28.448+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:19:28.447+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:19:28.480+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:19:28.473+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:19:28.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:19:28.509+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.076 seconds
[2024-05-23T16:19:58.765+0000] {processor.py:161} INFO - Started process (PID=1635) to work on /opt/airflow/dags/test.py
[2024-05-23T16:19:58.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:19:58.769+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:19:58.769+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:19:58.797+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:19:58.790+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:19:58.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:19:58.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.068 seconds
[2024-05-23T16:20:29.043+0000] {processor.py:161} INFO - Started process (PID=1642) to work on /opt/airflow/dags/test.py
[2024-05-23T16:20:29.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:20:29.047+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:20:29.047+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:20:29.079+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:20:29.070+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:20:29.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:20:29.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.078 seconds
[2024-05-23T16:20:59.314+0000] {processor.py:161} INFO - Started process (PID=1650) to work on /opt/airflow/dags/test.py
[2024-05-23T16:20:59.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:20:59.321+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:20:59.320+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:20:59.365+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:20:59.353+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:20:59.371+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:20:59.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.112 seconds
[2024-05-23T16:21:29.625+0000] {processor.py:161} INFO - Started process (PID=1657) to work on /opt/airflow/dags/test.py
[2024-05-23T16:21:29.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:21:29.630+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:21:29.629+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:21:29.661+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:21:29.653+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:21:29.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:21:29.688+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.073 seconds
[2024-05-23T16:21:59.899+0000] {processor.py:161} INFO - Started process (PID=1664) to work on /opt/airflow/dags/test.py
[2024-05-23T16:21:59.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:21:59.904+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:21:59.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:21:59.928+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:21:59.923+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:21:59.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:21:59.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.063 seconds
[2024-05-23T16:22:30.186+0000] {processor.py:161} INFO - Started process (PID=1671) to work on /opt/airflow/dags/test.py
[2024-05-23T16:22:30.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:22:30.190+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:22:30.190+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:22:30.220+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:22:30.212+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:22:30.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:22:30.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.071 seconds
[2024-05-23T16:23:00.557+0000] {processor.py:161} INFO - Started process (PID=1678) to work on /opt/airflow/dags/test.py
[2024-05-23T16:23:00.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:23:00.564+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:23:00.563+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:23:00.591+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:23:00.583+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:23:00.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:23:00.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.067 seconds
[2024-05-23T16:23:30.814+0000] {processor.py:161} INFO - Started process (PID=1685) to work on /opt/airflow/dags/test.py
[2024-05-23T16:23:30.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:23:30.819+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:23:30.819+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:23:30.844+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:23:30.838+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:23:30.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:23:30.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.065 seconds
[2024-05-23T16:24:01.118+0000] {processor.py:161} INFO - Started process (PID=1693) to work on /opt/airflow/dags/test.py
[2024-05-23T16:24:01.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:24:01.124+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:24:01.123+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:24:01.164+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:24:01.155+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:24:01.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:24:01.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.083 seconds
[2024-05-23T16:24:31.371+0000] {processor.py:161} INFO - Started process (PID=1700) to work on /opt/airflow/dags/test.py
[2024-05-23T16:24:31.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:24:31.375+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:24:31.375+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:24:31.401+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:24:31.395+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:24:31.405+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:24:31.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.063 seconds
[2024-05-23T16:25:01.677+0000] {processor.py:161} INFO - Started process (PID=1707) to work on /opt/airflow/dags/test.py
[2024-05-23T16:25:01.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:25:01.683+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:25:01.682+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:25:01.709+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:25:01.702+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:25:01.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:25:01.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.066 seconds
[2024-05-23T16:25:31.988+0000] {processor.py:161} INFO - Started process (PID=1714) to work on /opt/airflow/dags/test.py
[2024-05-23T16:25:31.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:25:31.995+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:25:31.994+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:25:32.046+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:25:32.032+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:25:32.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:25:32.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.120 seconds
[2024-05-23T16:41:09.051+0000] {processor.py:161} INFO - Started process (PID=1721) to work on /opt/airflow/dags/test.py
[2024-05-23T16:41:09.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-05-23T16:41:09.065+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:41:09.063+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-05-23T16:41:09.113+0000] {logging_mixin.py:188} INFO - [2024-05-23T16:41:09.099+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 5, in <module>
    "retry_delay": time
                   ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
[2024-05-23T16:41:09.121+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-05-23T16:41:09.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test.py took 0.214 seconds
