[2024-05-27T17:06:19.121+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T17:06:19.164+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: oltp_to_olap_transform.load_gcs_to_bq manual__2024-05-27T17:05:56.998620+00:00 [queued]>
[2024-05-27T17:06:19.199+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: oltp_to_olap_transform.load_gcs_to_bq manual__2024-05-27T17:05:56.998620+00:00 [queued]>
[2024-05-27T17:06:19.201+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 0
[2024-05-27T17:06:19.243+0000] {taskinstance.py:2330} INFO - Executing <Task(GCSToBigQueryOperator): load_gcs_to_bq> on 2024-05-27 17:05:56.998620+00:00
[2024-05-27T17:06:19.268+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-27T17:06:19.272+0000] {standard_task_runner.py:63} INFO - Started process 107 to run task
[2024-05-27T17:06:19.271+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'oltp_to_olap_transform', 'load_gcs_to_bq', 'manual__2024-05-27T17:05:56.998620+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/datawarehouse.py', '--cfg-path', '/tmp/tmpvnazzyua']
[2024-05-27T17:06:19.281+0000] {standard_task_runner.py:91} INFO - Job 102: Subtask load_gcs_to_bq
[2024-05-27T17:06:19.406+0000] {task_command.py:426} INFO - Running <TaskInstance: oltp_to_olap_transform.load_gcs_to_bq manual__2024-05-27T17:05:56.998620+00:00 [running]> on host 9b03efc10d80
[2024-05-27T17:06:19.800+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ngquynh' AIRFLOW_CTX_DAG_ID='oltp_to_olap_transform' AIRFLOW_CTX_TASK_ID='load_gcs_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2024-05-27T17:05:56.998620+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-27T17:05:56.998620+00:00'
[2024-05-27T17:06:19.808+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-27T17:06:19.995+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-27T17:06:20.008+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-05-27T17:06:20.019+0000] {gcs_to_bigquery.py:380} INFO - Using existing BigQuery table for storing data...
[2024-05-27T17:06:20.251+0000] {gcs_to_bigquery.py:384} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'datawarehouse-423912', 'datasetId': 'warehouse', 'tableId': 'categories'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://warehouse8/dataupdated/categories.csv'], 'writeDisposition': 'WRITE_EMPTY', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'categoryID', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'categoryName', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'description', 'type': 'STRING', 'mode': 'NULLABLE'}]}, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-05-27T17:06:20.254+0000] {bigquery.py:1660} INFO - Inserting job ***_oltp_to_olap_transform_load_gcs_to_bq_2024_05_27T17_05_56_998620_00_00_448f910f0928d92fb57de716e5697a6c
[2024-05-27T17:06:24.055+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-27T17:06:24.057+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 445, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 0; errors: 8; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 0; errors: 8; max bad: 0; error percent: 0; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 2 byte_offset_to_start_of_line: 36 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 3 byte_offset_to_start_of_line: 88 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 4 byte_offset_to_start_of_line: 157 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 5 byte_offset_to_start_of_line: 205 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 6 byte_offset_to_start_of_line: 230 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 7 byte_offset_to_start_of_line: 280 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 8 byte_offset_to_start_of_line: 310 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 9 byte_offset_to_start_of_line: 346 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv
[2024-05-27T17:06:24.113+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=oltp_to_olap_transform, task_id=load_gcs_to_bq, run_id=manual__2024-05-27T17:05:56.998620+00:00, execution_date=20240527T170556, start_date=20240527T170619, end_date=20240527T170624
[2024-05-27T17:06:24.158+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 102 for task load_gcs_to_bq (400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 0; errors: 8; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 0; errors: 8; max bad: 0; error percent: 0; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 2 byte_offset_to_start_of_line: 36 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 3 byte_offset_to_start_of_line: 88 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 4 byte_offset_to_start_of_line: 157 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 5 byte_offset_to_start_of_line: 205 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 6 byte_offset_to_start_of_line: 230 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 7 byte_offset_to_start_of_line: 280 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 8 byte_offset_to_start_of_line: 310 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; reason: invalid, location: gs://warehouse8/dataupdated/categories.csv, message: Error while reading data, error message: CSV table references column position 2, but line contains only 1 columns.; line_number: 9 byte_offset_to_start_of_line: 346 column_index: 2 column_name: "description" column_type: STRING File: gs://warehouse8/dataupdated/categories.csv; 107)
[2024-05-27T17:06:24.201+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-27T17:06:24.265+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-27T17:06:24.277+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
