[2024-05-28T09:03:29.407+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: oltp_to_olap_all_transform.create_Sale_Table manual__2024-05-28T09:03:12.641308+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
