[2024-05-28T12:36:20.302+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: loading_to_bigquerry.load_orderdetails_to_bq manual__2024-05-28T12:35:10.250918+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
