[2024-05-28T09:27:40.722+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T09:27:40.752+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: oltp_to_olap_all_transform.create_Sale_Table manual__2024-05-28T09:25:48.355557+00:00 [queued]>
[2024-05-28T09:27:40.769+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: oltp_to_olap_all_transform.create_Sale_Table manual__2024-05-28T09:25:48.355557+00:00 [queued]>
[2024-05-28T09:27:40.770+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 0
[2024-05-28T09:27:40.794+0000] {taskinstance.py:2330} INFO - Executing <Task(BigQueryInsertJobOperator): create_Sale_Table> on 2024-05-28 09:25:48.355557+00:00
[2024-05-28T09:27:40.807+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1115) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T09:27:40.810+0000] {standard_task_runner.py:63} INFO - Started process 1117 to run task
[2024-05-28T09:27:40.810+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'oltp_to_olap_all_transform', 'create_Sale_Table', 'manual__2024-05-28T09:25:48.355557+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/oltp_olap.py', '--cfg-path', '/tmp/tmpqe5nx72d']
[2024-05-28T09:27:40.814+0000] {standard_task_runner.py:91} INFO - Job 262: Subtask create_Sale_Table
[2024-05-28T09:27:40.885+0000] {task_command.py:426} INFO - Running <TaskInstance: oltp_to_olap_all_transform.create_Sale_Table manual__2024-05-28T09:25:48.355557+00:00 [running]> on host 9b03efc10d80
[2024-05-28T09:27:41.080+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ngquynh' AIRFLOW_CTX_DAG_ID='oltp_to_olap_all_transform' AIRFLOW_CTX_TASK_ID='create_Sale_Table' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T09:25:48.355557+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T09:25:48.355557+00:00'
[2024-05-28T09:27:41.083+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T09:27:41.128+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-28T09:27:41.132+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-05-28T09:27:41.209+0000] {bigquery.py:2832} INFO - Executing: {'query': {'query': 'CREATE TABLE or replace table `datawarehouse-423912.OLAP_dataset.Sale_table` AS\nSELECT \n    orderID,\n    SUM(quantity * unitprice * (1 - discount)) AS total_revenue\nFROM \n    `datawarehouse-423912.OLAP_dataset.Dim_Order_details`\nGROUP BY \n    orderID;', 'useLegacySql': False}}'
[2024-05-28T09:27:41.212+0000] {bigquery.py:1660} INFO - Inserting job ***_oltp_to_olap_all_transform_create_Sale_Table_2024_05_28T09_25_48_355557_00_00_f44254e5c105a7096899620de5ec7c66
[2024-05-28T09:27:46.578+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T09:27:46.579+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2891, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1626, in result
    while not is_job_done():
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1577, in is_job_done
    raise job_failed_exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected keyword OR at [1:14]; reason: invalidQuery, location: query, message: Syntax error: Unexpected keyword OR at [1:14]

Location: US
Job ID: airflow_oltp_to_olap_all_transform_create_Sale_Table_2024_05_28T09_25_48_355557_00_00_f44254e5c105a7096899620de5ec7c66

[2024-05-28T09:27:46.597+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=oltp_to_olap_all_transform, task_id=create_Sale_Table, run_id=manual__2024-05-28T09:25:48.355557+00:00, execution_date=20240528T092548, start_date=20240528T092740, end_date=20240528T092746
[2024-05-28T09:27:46.620+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 262 for task create_Sale_Table (400 Syntax error: Unexpected keyword OR at [1:14]; reason: invalidQuery, location: query, message: Syntax error: Unexpected keyword OR at [1:14]

Location: US
Job ID: airflow_oltp_to_olap_all_transform_create_Sale_Table_2024_05_28T09_25_48_355557_00_00_f44254e5c105a7096899620de5ec7c66
; 1117)
[2024-05-28T09:27:46.662+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T09:27:46.712+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T09:27:46.720+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
