[2024-05-26T17:44:10.730+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-26T17:44:10.793+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bigquery_example.run_bigquery_query manual__2024-05-26T17:43:35.553314+00:00 [queued]>
[2024-05-26T17:44:10.824+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bigquery_example.run_bigquery_query manual__2024-05-26T17:43:35.553314+00:00 [queued]>
[2024-05-26T17:44:10.827+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-26T17:44:10.892+0000] {taskinstance.py:2330} INFO - Executing <Task(BigQueryExecuteQueryOperator): run_bigquery_query> on 2024-05-26 17:43:35.553314+00:00
[2024-05-26T17:44:11.631+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-26T17:44:11.642+0000] {standard_task_runner.py:63} INFO - Started process 77 to run task
[2024-05-26T17:44:11.642+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bigquery_example', 'run_bigquery_query', 'manual__2024-05-26T17:43:35.553314+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpswyvr7cw']
[2024-05-26T17:44:11.651+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask run_bigquery_query
[2024-05-26T17:44:11.949+0000] {task_command.py:426} INFO - Running <TaskInstance: bigquery_example.run_bigquery_query manual__2024-05-26T17:43:35.553314+00:00 [running]> on host 6764b43dc9be
[2024-05-26T17:44:12.374+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nquynh' AIRFLOW_CTX_DAG_ID='bigquery_example' AIRFLOW_CTX_TASK_ID='run_bigquery_query' AIRFLOW_CTX_EXECUTION_DATE='2024-05-26T17:43:35.553314+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-26T17:43:35.553314+00:00'
[2024-05-26T17:44:12.383+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-26T17:44:12.532+0000] {bigquery.py:1252} INFO - Executing: 
        INSERT INTO `datawarehouse-423912.1.categories` 
        VALUES (2, "quynh")
            
[2024-05-26T17:44:12.569+0000] {base.py:84} INFO - Using connection ID 'google_cloud_datawarehouse' for task execution.
[2024-05-26T17:44:12.578+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/google/cloud/operators/bigquery.py:1261: AirflowProviderDeprecationWarning: Call to deprecated method run_query. (Please use `***.providers.google.cloud.hooks.bigquery.BigQueryHook.insert_job`)
  self.job_id = self.hook.run_query(

[2024-05-26T17:44:12.587+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-26T17:44:12.589+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1261, in execute
    self.job_id = self.hook.run_query(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/deprecated/classic.py", line 285, in wrapper_function
    return wrapped_(*args_, **kwargs_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2176, in run_query
    if not self.project_id:
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 373, in project_id
    _, project_id = self.get_credentials_and_project_id()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 285, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 362, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 235, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 286, in _get_credentials_using_key_path
    credentials = google.oauth2.service_account.Credentials.from_service_account_file(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/oauth2/service_account.py", line 258, in from_service_account_file
    info, signer = _service_account_info.from_filename(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'airflow\\gcs\\datawarehouse-423912-acebb524bd00.json'
[2024-05-26T17:44:12.640+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=bigquery_example, task_id=run_bigquery_query, run_id=manual__2024-05-26T17:43:35.553314+00:00, execution_date=20240526T174335, start_date=20240526T174410, end_date=20240526T174412
[2024-05-26T17:44:12.696+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task run_bigquery_query ([Errno 2] No such file or directory: 'airflow\\gcs\\datawarehouse-423912-acebb524bd00.json'; 77)
[2024-05-26T17:44:12.743+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-26T17:44:12.801+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26T17:44:12.811+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
