[2024-05-28T09:30:31.200+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T09:30:31.232+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: oltp_to_olap_all_transform.transform_Order_Fact_Table manual__2024-05-28T09:29:06.040118+00:00 [queued]>
[2024-05-28T09:30:31.250+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: oltp_to_olap_all_transform.transform_Order_Fact_Table manual__2024-05-28T09:29:06.040118+00:00 [queued]>
[2024-05-28T09:30:31.252+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 0
[2024-05-28T09:30:31.281+0000] {taskinstance.py:2330} INFO - Executing <Task(BigQueryInsertJobOperator): transform_Order_Fact_Table> on 2024-05-28 09:29:06.040118+00:00
[2024-05-28T09:30:31.297+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1175) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T09:30:31.300+0000] {standard_task_runner.py:63} INFO - Started process 1184 to run task
[2024-05-28T09:30:31.299+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'oltp_to_olap_all_transform', 'transform_Order_Fact_Table', 'manual__2024-05-28T09:29:06.040118+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/oltp_olap.py', '--cfg-path', '/tmp/tmp95kc3lx1']
[2024-05-28T09:30:31.305+0000] {standard_task_runner.py:91} INFO - Job 272: Subtask transform_Order_Fact_Table
[2024-05-28T09:30:31.397+0000] {task_command.py:426} INFO - Running <TaskInstance: oltp_to_olap_all_transform.transform_Order_Fact_Table manual__2024-05-28T09:29:06.040118+00:00 [running]> on host 9b03efc10d80
[2024-05-28T09:30:31.651+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ngquynh' AIRFLOW_CTX_DAG_ID='oltp_to_olap_all_transform' AIRFLOW_CTX_TASK_ID='transform_Order_Fact_Table' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T09:29:06.040118+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T09:29:06.040118+00:00'
[2024-05-28T09:30:31.654+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T09:30:31.694+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-28T09:30:31.699+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-05-28T09:30:31.779+0000] {bigquery.py:2832} INFO - Executing: {'query': {'query': 'create or replace table `datawarehouse-423912.OLAP_dataset.Order_fact_table` as\nwith RFM_table as (\n  select\n  fact.customer_id,\n  fact.order_id,\n  fact.order_date,\n  rfm.Recency,\n  rfm.Frequency,\n  rfm.Monetary,\n  sale.total_revenue\n  from\n  `datawarehouse-423912.OLAP_dataset.Fact_table_temp` as fact\n  join\n  `datawarehouse-423912.OLAP_dataset.RFM_table` as rfm\n  on \n fact.customer_id = rfm.customer_id\n  JOIN\n  `datawarehouse-423912.OLAP_dataset.sale_table_22` as sale\n  ON\n  fact.order_id = sale.orderID\n)\n\nselect * from RFM_table;', 'useLegacySql': False}}'
[2024-05-28T09:30:31.781+0000] {bigquery.py:1660} INFO - Inserting job ***_oltp_to_olap_all_transform_transform_Order_Fact_Table_2024_05_28T09_29_06_040118_00_00_57836336d6934a0739a9a87570291282
[2024-05-28T09:30:37.565+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T09:30:37.566+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2891, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1626, in result
    while not is_job_done():
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1577, in is_job_done
    raise job_failed_exception
google.api_core.exceptions.NotFound: 404 Not found: Table datawarehouse-423912:OLAP_dataset.sale_table_22 was not found in location US; reason: notFound, message: Not found: Table datawarehouse-423912:OLAP_dataset.sale_table_22 was not found in location US

Location: US
Job ID: airflow_oltp_to_olap_all_transform_transform_Order_Fact_Table_2024_05_28T09_29_06_040118_00_00_57836336d6934a0739a9a87570291282

[2024-05-28T09:30:37.591+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=oltp_to_olap_all_transform, task_id=transform_Order_Fact_Table, run_id=manual__2024-05-28T09:29:06.040118+00:00, execution_date=20240528T092906, start_date=20240528T093031, end_date=20240528T093037
[2024-05-28T09:30:37.621+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 272 for task transform_Order_Fact_Table (404 Not found: Table datawarehouse-423912:OLAP_dataset.sale_table_22 was not found in location US; reason: notFound, message: Not found: Table datawarehouse-423912:OLAP_dataset.sale_table_22 was not found in location US

Location: US
Job ID: airflow_oltp_to_olap_all_transform_transform_Order_Fact_Table_2024_05_28T09_29_06_040118_00_00_57836336d6934a0739a9a87570291282
; 1184)
[2024-05-28T09:30:37.663+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T09:30:37.688+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T09:30:37.693+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
