[2024-05-28T04:58:34.502+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: oltp_to_olap_transform.load_categories_to_bq manual__2024-05-28T04:58:31.689437+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
